### ISSUE TITLE
Railroader is not working yet

### ISSUE THREAD

**Issue by prabhu** [AppThreat/sast-scan#4]
From within a Ruby project

```bash
docker run --rm --tmpfs /tmp -e "WORKSPACE=${PWD}" -v $PWD:/app appthreat/sast-scan scan --src /app --out_dir /app/reports --type ruby
```

Leads to the following error

```bash
INFO [2020-01-12 16:53:28,438] ♒︎ Executing "railroader --skip-files .git,.svn,.mvn,.idea,dist,bin,obj,backup,docs,tests,test,tmp,reports -o /app/reports/ruby-report.json -q /app"
/usr/local/share/gems/gems/sexp_processor-4.13.0/lib/sexp.rb:222:in `line': setting s(:args).line nil (ArgumentError)
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/ruby_parser/bm_sexp.rb:43:in `deep_clone'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/ruby_parser/bm_sexp.rb:32:in `block in deep_clone'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/ruby_parser/bm_sexp.rb:30:in `each'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/ruby_parser/bm_sexp.rb:30:in `deep_clone'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/processors/alias_processor.rb:50:in `process_safely'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/processor.rb:93:in `process_initializer'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/scanner.rb:185:in `process_initializer'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/scanner.rb:179:in `block in process_initializers'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/scanner.rb:302:in `block in track_progress'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/scanner.rb:299:in `each'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/scanner.rb:299:in `track_progress'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/scanner.rb:177:in `process_initializers'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/scanner.rb:47:in `process'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader.rb:354:in `scan'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader.rb:77:in `run'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/commandline.rb:133:in `run_railroader'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/commandline.rb:118:in `regular_report'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/commandline.rb:142:in `run_report'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/commandline.rb:35:in `run'
	from /usr/local/share/gems/gems/railroader-4.3.8/lib/railroader/commandline.rb:20:in `start'
	from /usr/local/share/gems/gems/railroader-4.3.8/bin/railroader:8:in `<top (required)>'
	from /usr/local/bin/railroader:23:in `load'
	from /usr/local/bin/railroader:23:in `<main>'
```

Referenced issue: https://github.com/david-a-wheeler/railroader/issues/7

**Comment by prabhu** [comment]
With regret, I have removed railroader from sast-scan. Hopefully, there will be a better oss sast product for ruby in the future.
